"""
FedRAMP Moderate Baseline Controls

NIST 800-53 Rev 5 controls mapped to the FedRAMP Moderate baseline.
Each control includes its family, title, description, priority,
and a mapping to the PySOAR feature that implements it.
"""

FEDRAMP_MODERATE_CONTROLS = [
    # =========================================================================
    # AC — Access Control
    # =========================================================================
    {
        "id": "AC-1",
        "family": "Access Control",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate access control policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Security Policies",
    },
    {
        "id": "AC-2",
        "family": "Access Control",
        "title": "Account Management",
        "description": "Manage system accounts including creating, enabling, modifying, disabling, and removing accounts.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "User Management Module",
    },
    {
        "id": "AC-3",
        "family": "Access Control",
        "title": "Access Enforcement",
        "description": "Enforce approved authorizations for logical access to information and system resources.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "RBAC / Zero Trust Module",
    },
    {
        "id": "AC-4",
        "family": "Access Control",
        "title": "Information Flow Enforcement",
        "description": "Enforce approved authorizations for controlling the flow of information within the system and between systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "DLP Module / Network Segmentation",
    },
    {
        "id": "AC-5",
        "family": "Access Control",
        "title": "Separation of Duties",
        "description": "Separate duties of individuals to prevent malicious activity without collusion.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "RBAC Role Separation",
    },
    {
        "id": "AC-6",
        "family": "Access Control",
        "title": "Least Privilege",
        "description": "Employ the principle of least privilege, allowing only authorized accesses necessary to accomplish assigned tasks.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Zero Trust Module / RBAC",
    },
    {
        "id": "AC-7",
        "family": "Access Control",
        "title": "Unsuccessful Logon Attempts",
        "description": "Enforce a limit of consecutive invalid logon attempts and automatically lock accounts.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Auth Module — Lockout Policy",
    },
    {
        "id": "AC-8",
        "family": "Access Control",
        "title": "System Use Notification",
        "description": "Display an approved system use notification banner before granting access.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Login Banner Configuration",
    },
    {
        "id": "AC-10",
        "family": "Access Control",
        "title": "Concurrent Session Control",
        "description": "Limit the number of concurrent sessions for each account.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Session Management",
    },
    {
        "id": "AC-11",
        "family": "Access Control",
        "title": "Device Lock",
        "description": "Prevent further access to the system by initiating a device lock after inactivity.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Session Timeout Settings",
    },
    {
        "id": "AC-12",
        "family": "Access Control",
        "title": "Session Termination",
        "description": "Automatically terminate a user session after defined conditions.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Session Management",
    },
    {
        "id": "AC-14",
        "family": "Access Control",
        "title": "Permitted Actions Without Identification or Authentication",
        "description": "Identify user actions that can be performed without identification or authentication.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "API Security — Public Endpoints",
    },
    {
        "id": "AC-17",
        "family": "Access Control",
        "title": "Remote Access",
        "description": "Establish and document usage restrictions and implementation guidance for remote access.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "VPN / MFA Module",
    },
    {
        "id": "AC-18",
        "family": "Access Control",
        "title": "Wireless Access",
        "description": "Establish usage restrictions and implementation guidance for wireless access.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Network Security Policies",
    },
    {
        "id": "AC-19",
        "family": "Access Control",
        "title": "Access Control for Mobile Devices",
        "description": "Establish usage restrictions and implementation guidance for mobile device access.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "ITDR / Device Trust Module",
    },
    {
        "id": "AC-20",
        "family": "Access Control",
        "title": "Use of External Systems",
        "description": "Establish terms and conditions for authorized use of external systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Integration Management",
    },
    {
        "id": "AC-21",
        "family": "Access Control",
        "title": "Information Sharing",
        "description": "Facilitate information sharing enabling authorized users to share information.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Collaboration / Intel Sharing",
    },
    {
        "id": "AC-22",
        "family": "Access Control",
        "title": "Publicly Accessible Content",
        "description": "Designate individuals authorized to post information onto a publicly accessible system.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Content Publishing Controls",
    },
    # =========================================================================
    # AT — Awareness and Training
    # =========================================================================
    {
        "id": "AT-1",
        "family": "Awareness and Training",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate security awareness and training policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Training Policies",
    },
    {
        "id": "AT-2",
        "family": "Awareness and Training",
        "title": "Literacy Training and Awareness",
        "description": "Provide security literacy training to system users including awareness of threats and basic safeguards.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Phishing Simulation Module",
    },
    {
        "id": "AT-3",
        "family": "Awareness and Training",
        "title": "Role-Based Training",
        "description": "Provide role-based security training before authorizing access to the system.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Phishing Simulation — Role Training",
    },
    {
        "id": "AT-4",
        "family": "Awareness and Training",
        "title": "Training Records",
        "description": "Document and monitor individual security training activities.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Evidence Module — Training Records",
    },
    # =========================================================================
    # AU — Audit and Accountability
    # =========================================================================
    {
        "id": "AU-1",
        "family": "Audit and Accountability",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate audit and accountability policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Audit Policies",
    },
    {
        "id": "AU-2",
        "family": "Audit and Accountability",
        "title": "Event Logging",
        "description": "Identify the types of events that the system is capable of logging.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Logging Module",
    },
    {
        "id": "AU-3",
        "family": "Audit and Accountability",
        "title": "Content of Audit Records",
        "description": "Ensure audit records contain what, when, where, source, outcome, and identity.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Logging — Record Format",
    },
    {
        "id": "AU-4",
        "family": "Audit and Accountability",
        "title": "Audit Log Storage Capacity",
        "description": "Allocate audit log storage capacity and configure audit log storage.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Data Lake / Log Storage",
    },
    {
        "id": "AU-5",
        "family": "Audit and Accountability",
        "title": "Response to Audit Logging Process Failures",
        "description": "Alert personnel or roles in the event of an audit logging process failure.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM Alerting — System Health",
    },
    {
        "id": "AU-6",
        "family": "Audit and Accountability",
        "title": "Audit Record Review, Analysis, and Reporting",
        "description": "Review and analyze system audit records for indications of inappropriate activity.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM Module / UEBA",
    },
    {
        "id": "AU-7",
        "family": "Audit and Accountability",
        "title": "Audit Record Reduction and Report Generation",
        "description": "Provide and implement an audit record reduction and report generation capability.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM Dashboards and Reports",
    },
    {
        "id": "AU-8",
        "family": "Audit and Accountability",
        "title": "Time Stamps",
        "description": "Use internal system clocks to generate time stamps for audit records.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "NTP Synchronization / Audit Timestamps",
    },
    {
        "id": "AU-9",
        "family": "Audit and Accountability",
        "title": "Protection of Audit Information",
        "description": "Protect audit information and audit logging tools from unauthorized access.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Log Integrity / RBAC",
    },
    {
        "id": "AU-10",
        "family": "Audit and Accountability",
        "title": "Non-Repudiation",
        "description": "Provide irrefutable evidence that an action was performed.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Trail / Digital Signatures",
    },
    {
        "id": "AU-11",
        "family": "Audit and Accountability",
        "title": "Audit Record Retention",
        "description": "Retain audit records for the defined retention period.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Data Lake Retention Policies",
    },
    {
        "id": "AU-12",
        "family": "Audit and Accountability",
        "title": "Audit Record Generation",
        "description": "Provide audit record generation capability for the events defined in AU-2.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Logging Engine",
    },
    # =========================================================================
    # CA — Security Assessment and Authorization
    # =========================================================================
    {
        "id": "CA-1",
        "family": "Security Assessment and Authorization",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate security assessment and authorization policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — Assessment Policies",
    },
    {
        "id": "CA-2",
        "family": "Security Assessment and Authorization",
        "title": "Control Assessments",
        "description": "Develop a control assessment plan and assess controls to determine implementation effectiveness.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — Control Assessments",
    },
    {
        "id": "CA-3",
        "family": "Security Assessment and Authorization",
        "title": "Information Exchange",
        "description": "Approve and manage the exchange of information between the system and other systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Integration Management / API Security",
    },
    {
        "id": "CA-5",
        "family": "Security Assessment and Authorization",
        "title": "Plan of Action and Milestones",
        "description": "Develop and update a POA&M for the system to document planned remedial actions.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — POA&M Tracker",
    },
    {
        "id": "CA-6",
        "family": "Security Assessment and Authorization",
        "title": "Authorization",
        "description": "Authorize the system for processing before commencing operations.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — ATO Management",
    },
    {
        "id": "CA-7",
        "family": "Security Assessment and Authorization",
        "title": "Continuous Monitoring",
        "description": "Develop a continuous monitoring strategy and implement a continuous monitoring program.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM / Continuous Monitoring Dashboard",
    },
    {
        "id": "CA-8",
        "family": "Security Assessment and Authorization",
        "title": "Penetration Testing",
        "description": "Conduct penetration testing at defined frequency on defined systems.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Vulnerability Management — Pen Test Tracking",
    },
    {
        "id": "CA-9",
        "family": "Security Assessment and Authorization",
        "title": "Internal System Connections",
        "description": "Authorize internal connections of system components and document connection characteristics.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Asset Management — Network Connections",
    },
    # =========================================================================
    # CM — Configuration Management
    # =========================================================================
    {
        "id": "CM-1",
        "family": "Configuration Management",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate configuration management policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Configuration Policies",
    },
    {
        "id": "CM-2",
        "family": "Configuration Management",
        "title": "Baseline Configuration",
        "description": "Develop, document, and maintain baseline configurations for the system.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "STIG Module / Container Security Baselines",
    },
    {
        "id": "CM-3",
        "family": "Configuration Management",
        "title": "Configuration Change Control",
        "description": "Determine and document types of changes that are configuration-controlled.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Change Management / Git Version Control",
    },
    {
        "id": "CM-4",
        "family": "Configuration Management",
        "title": "Impact Analyses",
        "description": "Analyze changes to the system to determine potential security and privacy impacts.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification Module",
    },
    {
        "id": "CM-5",
        "family": "Configuration Management",
        "title": "Access Restrictions for Change",
        "description": "Define and enforce access restrictions associated with changes to the system.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "RBAC — Change Approval Workflow",
    },
    {
        "id": "CM-6",
        "family": "Configuration Management",
        "title": "Configuration Settings",
        "description": "Establish and document configuration settings for system components.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "STIG Module / Hardening Baselines",
    },
    {
        "id": "CM-7",
        "family": "Configuration Management",
        "title": "Least Functionality",
        "description": "Configure the system to provide only mission-essential capabilities.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Container Security — Minimal Images",
    },
    {
        "id": "CM-8",
        "family": "Configuration Management",
        "title": "System Component Inventory",
        "description": "Develop and document an inventory of system components.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Asset Management Module",
    },
    {
        "id": "CM-9",
        "family": "Configuration Management",
        "title": "Configuration Management Plan",
        "description": "Develop, document, and implement a configuration management plan.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — CM Plan",
    },
    {
        "id": "CM-10",
        "family": "Configuration Management",
        "title": "Software Usage Restrictions",
        "description": "Use software and associated documentation in accordance with license agreements.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Supply Chain Module — License Tracking",
    },
    {
        "id": "CM-11",
        "family": "Configuration Management",
        "title": "User-Installed Software",
        "description": "Establish and enforce restrictions governing the installation of software by users.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Container Security — Image Allow-list",
    },
    # =========================================================================
    # CP — Contingency Planning
    # =========================================================================
    {
        "id": "CP-1",
        "family": "Contingency Planning",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate contingency planning policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > DR Policies",
    },
    {
        "id": "CP-2",
        "family": "Contingency Planning",
        "title": "Contingency Plan",
        "description": "Develop a contingency plan that identifies essential mission functions and recovery objectives.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Backup / Disaster Recovery Runbooks",
    },
    {
        "id": "CP-3",
        "family": "Contingency Planning",
        "title": "Contingency Training",
        "description": "Provide contingency training to system users consistent with assigned roles.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Simulation Module — DR Exercises",
    },
    {
        "id": "CP-4",
        "family": "Contingency Planning",
        "title": "Contingency Plan Testing",
        "description": "Test the contingency plan at defined frequency to determine effectiveness.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Simulation Module — DR Testing",
    },
    {
        "id": "CP-6",
        "family": "Contingency Planning",
        "title": "Alternate Storage Site",
        "description": "Establish an alternate storage site and initiate agreements for storage of backup information.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Backup Module — Offsite Storage",
    },
    {
        "id": "CP-7",
        "family": "Contingency Planning",
        "title": "Alternate Processing Site",
        "description": "Establish an alternate processing site that permits transfer of operations.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Multi-Cloud Terraform Deployment",
    },
    {
        "id": "CP-8",
        "family": "Contingency Planning",
        "title": "Telecommunications Services",
        "description": "Establish alternate telecommunications services for essential operations.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Network Redundancy Configuration",
    },
    {
        "id": "CP-9",
        "family": "Contingency Planning",
        "title": "System Backup",
        "description": "Conduct backups of user-level and system-level information at defined frequency.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Backup Module",
    },
    {
        "id": "CP-10",
        "family": "Contingency Planning",
        "title": "System Recovery and Reconstitution",
        "description": "Provide for the recovery and reconstitution of the system to a known state.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Backup Module — Recovery Procedures",
    },
    {
        "id": "CP-12",
        "family": "Contingency Planning",
        "title": "Safe Mode",
        "description": "When certain conditions are detected, enter a safe mode of operation with restricted capability.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Remediation — Automated Containment",
    },
    {
        "id": "CP-13",
        "family": "Contingency Planning",
        "title": "Alternative Security Mechanisms",
        "description": "Employ alternative or supplemental security mechanisms when primary means are unavailable.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Zero Trust — Fallback Policies",
    },
    # =========================================================================
    # IA — Identification and Authentication
    # =========================================================================
    {
        "id": "IA-1",
        "family": "Identification and Authentication",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate identification and authentication policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Authentication Policies",
    },
    {
        "id": "IA-2",
        "family": "Identification and Authentication",
        "title": "Identification and Authentication (Organizational Users)",
        "description": "Uniquely identify and authenticate organizational users.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Auth Module / MFA",
    },
    {
        "id": "IA-3",
        "family": "Identification and Authentication",
        "title": "Device Identification and Authentication",
        "description": "Uniquely identify and authenticate devices before establishing a connection.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "ITDR — Device Trust",
    },
    {
        "id": "IA-4",
        "family": "Identification and Authentication",
        "title": "Identifier Management",
        "description": "Manage system identifiers by receiving authorization and issuing identifiers.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Identity Lifecycle",
    },
    {
        "id": "IA-5",
        "family": "Identification and Authentication",
        "title": "Authenticator Management",
        "description": "Manage system authenticators by verifying identity before initial distribution.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Auth Module — Password / Token Management",
    },
    {
        "id": "IA-6",
        "family": "Identification and Authentication",
        "title": "Authentication Feedback",
        "description": "Obscure feedback of authentication information during the authentication process.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Auth Module — Masked Input",
    },
    {
        "id": "IA-7",
        "family": "Identification and Authentication",
        "title": "Cryptographic Module Authentication",
        "description": "Implement mechanisms for authentication to a cryptographic module.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "TLS / Certificate Management",
    },
    {
        "id": "IA-8",
        "family": "Identification and Authentication",
        "title": "Identification and Authentication (Non-Organizational Users)",
        "description": "Uniquely identify and authenticate non-organizational users.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "API Key Management / OAuth",
    },
    {
        "id": "IA-9",
        "family": "Identification and Authentication",
        "title": "Service Identification and Authentication",
        "description": "Identify and authenticate services before establishing communications.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "API Security — Service Auth",
    },
    {
        "id": "IA-10",
        "family": "Identification and Authentication",
        "title": "Adaptive Authentication",
        "description": "Require users to provide additional authentication factors when defined conditions are met.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "UEBA — Adaptive MFA",
    },
    {
        "id": "IA-11",
        "family": "Identification and Authentication",
        "title": "Re-authentication",
        "description": "Require users to re-authenticate when defined circumstances or situations apply.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Session Management — Re-auth",
    },
    {
        "id": "IA-12",
        "family": "Identification and Authentication",
        "title": "Identity Proofing",
        "description": "Identity proof users that require accounts and resolve each identity to a unique individual.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Identity Verification",
    },
    # =========================================================================
    # IR — Incident Response
    # =========================================================================
    {
        "id": "IR-1",
        "family": "Incident Response",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate an incident response policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Incident Response Module — Policies",
    },
    {
        "id": "IR-2",
        "family": "Incident Response",
        "title": "Incident Response Training",
        "description": "Provide incident response training to system users consistent with assigned roles.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Simulation Module — IR Training",
    },
    {
        "id": "IR-3",
        "family": "Incident Response",
        "title": "Incident Response Testing",
        "description": "Test the incident response capability at defined frequency.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Simulation Module — Tabletop Exercises",
    },
    {
        "id": "IR-4",
        "family": "Incident Response",
        "title": "Incident Handling",
        "description": "Implement incident handling capability including preparation, detection, analysis, containment, eradication, and recovery.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Incident Response Module",
    },
    {
        "id": "IR-5",
        "family": "Incident Response",
        "title": "Incident Monitoring",
        "description": "Track and document incidents on an ongoing basis.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM / Case Management",
    },
    {
        "id": "IR-6",
        "family": "Incident Response",
        "title": "Incident Reporting",
        "description": "Require personnel to report suspected incidents to the incident response capability.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Incident Response — Reporting Workflow",
    },
    {
        "id": "IR-7",
        "family": "Incident Response",
        "title": "Incident Response Assistance",
        "description": "Provide an incident response support resource that offers advice and assistance.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Agentic SOC / War Room",
    },
    {
        "id": "IR-8",
        "family": "Incident Response",
        "title": "Incident Response Plan",
        "description": "Develop an incident response plan that provides a roadmap for incident response capability.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Playbook Builder — IR Playbooks",
    },
    {
        "id": "IR-9",
        "family": "Incident Response",
        "title": "Information Spillage Response",
        "description": "Respond to information spills by identifying and addressing the contamination.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "DLP Module — Spill Response",
    },
    {
        "id": "IR-10",
        "family": "Incident Response",
        "title": "Integrated Information Security Analysis Team",
        "description": "Establish an integrated team for investigating and responding to incidents.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Collaboration — War Room / DFIR Team",
    },
    # =========================================================================
    # MA — Maintenance
    # =========================================================================
    {
        "id": "MA-1",
        "family": "Maintenance",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate system maintenance policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Maintenance Policies",
    },
    {
        "id": "MA-2",
        "family": "Maintenance",
        "title": "Controlled Maintenance",
        "description": "Schedule, document, and review records of maintenance and repairs on system components.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Change Management / Maintenance Windows",
    },
    {
        "id": "MA-3",
        "family": "Maintenance",
        "title": "Maintenance Tools",
        "description": "Approve, control, and monitor the use of system maintenance tools.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Asset Management — Tool Inventory",
    },
    {
        "id": "MA-4",
        "family": "Maintenance",
        "title": "Nonlocal Maintenance",
        "description": "Approve and monitor nonlocal maintenance and diagnostic activities.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Remote Access / VPN Maintenance",
    },
    {
        "id": "MA-5",
        "family": "Maintenance",
        "title": "Maintenance Personnel",
        "description": "Establish a process for maintenance personnel authorization.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Maintenance Roles",
    },
    {
        "id": "MA-6",
        "family": "Maintenance",
        "title": "Timely Maintenance",
        "description": "Obtain maintenance support and spare parts within defined time period of failure.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "SLA Management / Vendor Contracts",
    },
    # =========================================================================
    # MP — Media Protection
    # =========================================================================
    {
        "id": "MP-1",
        "family": "Media Protection",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate media protection policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Data Protection Policies",
    },
    {
        "id": "MP-2",
        "family": "Media Protection",
        "title": "Media Access",
        "description": "Restrict access to digital and non-digital media to authorized individuals.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "DLP Module / RBAC",
    },
    {
        "id": "MP-3",
        "family": "Media Protection",
        "title": "Media Marking",
        "description": "Mark system media indicating distribution limitations and handling caveats.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Privacy Module — Data Classification",
    },
    {
        "id": "MP-4",
        "family": "Media Protection",
        "title": "Media Storage",
        "description": "Physically control and securely store digital and non-digital media.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Data Lake — Encrypted Storage",
    },
    {
        "id": "MP-5",
        "family": "Media Protection",
        "title": "Media Transport",
        "description": "Protect and control digital and non-digital media during transport.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "DLP Module — Data in Transit",
    },
    {
        "id": "MP-6",
        "family": "Media Protection",
        "title": "Media Sanitization",
        "description": "Sanitize system media prior to disposal, release, or reuse.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Data Lifecycle — Secure Deletion",
    },
    {
        "id": "MP-7",
        "family": "Media Protection",
        "title": "Media Use",
        "description": "Restrict the use of certain types of media on systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Endpoint Security Policies",
    },
    {
        "id": "MP-8",
        "family": "Media Protection",
        "title": "Media Downgrading",
        "description": "Establish and document media downgrading process for system media.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Privacy Module — Data Reclassification",
    },
    # =========================================================================
    # PE — Physical and Environmental Protection
    # =========================================================================
    {
        "id": "PE-1",
        "family": "Physical and Environmental Protection",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate physical and environmental protection policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Physical Security Policies",
    },
    {
        "id": "PE-2",
        "family": "Physical and Environmental Protection",
        "title": "Physical Access Authorizations",
        "description": "Develop, approve, and maintain a list of individuals with authorized physical access.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Asset Management — Facility Access",
    },
    {
        "id": "PE-3",
        "family": "Physical and Environmental Protection",
        "title": "Physical Access Control",
        "description": "Enforce physical access authorizations at entry and exit points.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Physical Security Integration",
    },
    {
        "id": "PE-4",
        "family": "Physical and Environmental Protection",
        "title": "Access Control for Transmission",
        "description": "Control physical access to system distribution and transmission lines.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Network Infrastructure Security",
    },
    {
        "id": "PE-5",
        "family": "Physical and Environmental Protection",
        "title": "Access Control for Output Devices",
        "description": "Control physical access to output from system output devices.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "DLP — Print/Export Controls",
    },
    {
        "id": "PE-6",
        "family": "Physical and Environmental Protection",
        "title": "Monitoring Physical Access",
        "description": "Monitor physical access to the facility to detect and respond to incidents.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM — Physical Access Log Ingestion",
    },
    {
        "id": "PE-8",
        "family": "Physical and Environmental Protection",
        "title": "Visitor Access Records",
        "description": "Maintain visitor access records to the facility.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Audit Evidence — Visitor Logs",
    },
    {
        "id": "PE-9",
        "family": "Physical and Environmental Protection",
        "title": "Power Equipment and Cabling",
        "description": "Protect power equipment and power cabling for the system.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Infrastructure Monitoring",
    },
    {
        "id": "PE-10",
        "family": "Physical and Environmental Protection",
        "title": "Emergency Shutoff",
        "description": "Provide the capability of shutting off power to the system in emergency situations.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Emergency Procedures / Runbooks",
    },
    {
        "id": "PE-11",
        "family": "Physical and Environmental Protection",
        "title": "Emergency Power",
        "description": "Provide an uninterruptible power supply to facilitate an orderly shutdown.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Infrastructure — UPS/Generator Monitoring",
    },
    {
        "id": "PE-12",
        "family": "Physical and Environmental Protection",
        "title": "Emergency Lighting",
        "description": "Employ and maintain automatic emergency lighting for the facility.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Facility Management",
    },
    {
        "id": "PE-13",
        "family": "Physical and Environmental Protection",
        "title": "Fire Protection",
        "description": "Employ and maintain fire detection and suppression systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Facility Management — Fire Systems",
    },
    {
        "id": "PE-14",
        "family": "Physical and Environmental Protection",
        "title": "Environmental Controls",
        "description": "Maintain temperature and humidity levels within the facility.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Infrastructure Monitoring — HVAC",
    },
    {
        "id": "PE-15",
        "family": "Physical and Environmental Protection",
        "title": "Water Damage Protection",
        "description": "Protect the system from damage resulting from water leakage.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Facility Management — Water Detection",
    },
    {
        "id": "PE-16",
        "family": "Physical and Environmental Protection",
        "title": "Delivery and Removal",
        "description": "Authorize and control system components entering and exiting the facility.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Asset Management — Hardware Tracking",
    },
    {
        "id": "PE-17",
        "family": "Physical and Environmental Protection",
        "title": "Alternate Work Site",
        "description": "Employ management, operational, and technical controls at alternate work sites.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Remote Access / Zero Trust",
    },
    {
        "id": "PE-18",
        "family": "Physical and Environmental Protection",
        "title": "Location of System Components",
        "description": "Position system components to minimize potential damage from physical and environmental hazards.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Infrastructure Architecture",
    },
    # =========================================================================
    # PL — Planning
    # =========================================================================
    {
        "id": "PL-1",
        "family": "Planning",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate security planning policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — Security Planning",
    },
    {
        "id": "PL-2",
        "family": "Planning",
        "title": "System Security and Privacy Plans",
        "description": "Develop, review, update, and protect the system security plan.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "FedRAMP Module — SSP Generator",
    },
    {
        "id": "PL-4",
        "family": "Planning",
        "title": "Rules of Behavior",
        "description": "Establish and provide rules that describe responsibilities and expected behavior.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Acceptable Use Policy",
    },
    {
        "id": "PL-8",
        "family": "Planning",
        "title": "Security and Privacy Architectures",
        "description": "Develop security and privacy architectures that describe the overall philosophy and approach.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Threat Modeling Module",
    },
    {
        "id": "PL-9",
        "family": "Planning",
        "title": "Central Management",
        "description": "Centrally manage security controls and related processes.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Unified Security Dashboard",
    },
    # =========================================================================
    # PS — Personnel Security
    # =========================================================================
    {
        "id": "PS-1",
        "family": "Personnel Security",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate personnel security policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Personnel Policies",
    },
    {
        "id": "PS-2",
        "family": "Personnel Security",
        "title": "Position Risk Designation",
        "description": "Assign a risk designation to all organizational positions.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Role Risk Levels",
    },
    {
        "id": "PS-3",
        "family": "Personnel Security",
        "title": "Personnel Screening",
        "description": "Screen individuals prior to authorizing access to the system.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Background Check Tracking",
    },
    {
        "id": "PS-4",
        "family": "Personnel Security",
        "title": "Personnel Termination",
        "description": "Upon termination, disable system access and retrieve all credentials.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Offboarding Workflow",
    },
    {
        "id": "PS-5",
        "family": "Personnel Security",
        "title": "Personnel Transfer",
        "description": "Review and confirm ongoing operational need when individuals are reassigned.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "User Management — Access Review",
    },
    {
        "id": "PS-6",
        "family": "Personnel Security",
        "title": "Access Agreements",
        "description": "Require individuals accessing the system to sign access agreements.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — Access Agreements",
    },
    {
        "id": "PS-7",
        "family": "Personnel Security",
        "title": "External Personnel Security",
        "description": "Establish personnel security requirements for external providers.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Supply Chain — Vendor Security",
    },
    {
        "id": "PS-8",
        "family": "Personnel Security",
        "title": "Personnel Sanctions",
        "description": "Employ a formal sanctions process for individuals failing to comply with policies.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Disciplinary Policies",
    },
    # =========================================================================
    # RA — Risk Assessment
    # =========================================================================
    {
        "id": "RA-1",
        "family": "Risk Assessment",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate risk assessment policy and procedures.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification Module — Policies",
    },
    {
        "id": "RA-2",
        "family": "Risk Assessment",
        "title": "Security Categorization",
        "description": "Categorize the system and information processed in accordance with FIPS 199.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — FIPS 199 Categorization",
    },
    {
        "id": "RA-3",
        "family": "Risk Assessment",
        "title": "Risk Assessment",
        "description": "Conduct an assessment of risk including likelihood and magnitude of harm.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification Module",
    },
    {
        "id": "RA-5",
        "family": "Risk Assessment",
        "title": "Vulnerability Monitoring and Scanning",
        "description": "Monitor and scan for vulnerabilities in the system at defined frequency.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Vulnerability Management Module",
    },
    # =========================================================================
    # SA — System and Services Acquisition
    # =========================================================================
    {
        "id": "SA-1",
        "family": "System and Services Acquisition",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate system and services acquisition policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Acquisition Policies",
    },
    {
        "id": "SA-2",
        "family": "System and Services Acquisition",
        "title": "Allocation of Resources",
        "description": "Determine security requirements for the system in mission/business process planning.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification — Resource Planning",
    },
    {
        "id": "SA-3",
        "family": "System and Services Acquisition",
        "title": "System Development Life Cycle",
        "description": "Manage the system using a system development life cycle methodology.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "CI/CD Pipeline / DevSecOps",
    },
    {
        "id": "SA-4",
        "family": "System and Services Acquisition",
        "title": "Acquisition Process",
        "description": "Include security and privacy requirements in the acquisition contract.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Supply Chain Module — Vendor Assessment",
    },
    {
        "id": "SA-5",
        "family": "System and Services Acquisition",
        "title": "System Documentation",
        "description": "Obtain and protect required administrator and user documentation.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Documentation / Runbooks",
    },
    {
        "id": "SA-8",
        "family": "System and Services Acquisition",
        "title": "Security and Privacy Engineering Principles",
        "description": "Apply security and privacy engineering principles to system design.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Threat Modeling / Secure Architecture",
    },
    {
        "id": "SA-9",
        "family": "System and Services Acquisition",
        "title": "External System Services",
        "description": "Require that providers of external services comply with security requirements.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Supply Chain — Third-Party Risk",
    },
    {
        "id": "SA-10",
        "family": "System and Services Acquisition",
        "title": "Developer Configuration Management",
        "description": "Require the developer to perform configuration management during development.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "CI/CD — Build Configuration",
    },
    {
        "id": "SA-11",
        "family": "System and Services Acquisition",
        "title": "Developer Testing and Evaluation",
        "description": "Require the developer to create a security assessment plan and implement testing.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "CI/CD — Security Testing (SAST/DAST)",
    },
    {
        "id": "SA-15",
        "family": "System and Services Acquisition",
        "title": "Development Process, Standards, and Tools",
        "description": "Require the developer to follow a documented development process.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Supply Chain — SBOM / Dev Standards",
    },
    {
        "id": "SA-22",
        "family": "System and Services Acquisition",
        "title": "Unsupported System Components",
        "description": "Replace system components when support is no longer available.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Vulnerability Management — EOL Tracking",
    },
    # =========================================================================
    # SC — System and Communications Protection
    # =========================================================================
    {
        "id": "SC-1",
        "family": "System and Communications Protection",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate system and communications protection policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Communications Policies",
    },
    {
        "id": "SC-2",
        "family": "System and Communications Protection",
        "title": "Separation of System and User Functionality",
        "description": "Separate user functionality from system management functionality.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Architecture — Admin/User Separation",
    },
    {
        "id": "SC-4",
        "family": "System and Communications Protection",
        "title": "Information in Shared System Resources",
        "description": "Prevent unauthorized and unintended information transfer via shared system resources.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Container Security — Resource Isolation",
    },
    {
        "id": "SC-5",
        "family": "System and Communications Protection",
        "title": "Denial-of-Service Protection",
        "description": "Protect against or limit the effects of denial-of-service attacks.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "API Security — Rate Limiting / WAF",
    },
    {
        "id": "SC-7",
        "family": "System and Communications Protection",
        "title": "Boundary Protection",
        "description": "Monitor and control communications at the external managed interfaces.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Zero Trust / Network Segmentation",
    },
    {
        "id": "SC-8",
        "family": "System and Communications Protection",
        "title": "Transmission Confidentiality and Integrity",
        "description": "Protect the confidentiality and integrity of transmitted information.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "TLS Encryption / mTLS",
    },
    {
        "id": "SC-10",
        "family": "System and Communications Protection",
        "title": "Network Disconnect",
        "description": "Terminate the network connection at the end of a session or after inactivity.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Session Management — Network Timeout",
    },
    {
        "id": "SC-12",
        "family": "System and Communications Protection",
        "title": "Cryptographic Key Establishment and Management",
        "description": "Establish and manage cryptographic keys using approved key management technology.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Key Management / Certificate Rotation",
    },
    {
        "id": "SC-13",
        "family": "System and Communications Protection",
        "title": "Cryptographic Protection",
        "description": "Implement FIPS-validated cryptography to protect information.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Encryption Module — FIPS 140-2",
    },
    {
        "id": "SC-15",
        "family": "System and Communications Protection",
        "title": "Collaborative Computing Devices and Applications",
        "description": "Prohibit remote activation of collaborative computing devices.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Collaboration — Security Controls",
    },
    {
        "id": "SC-17",
        "family": "System and Communications Protection",
        "title": "Public Key Infrastructure Certificates",
        "description": "Issue public key certificates under an appropriate certificate policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Certificate Management / PKI",
    },
    {
        "id": "SC-18",
        "family": "System and Communications Protection",
        "title": "Mobile Code",
        "description": "Define acceptable and unacceptable mobile code and technologies.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "API Security — Code Execution Policies",
    },
    {
        "id": "SC-20",
        "family": "System and Communications Protection",
        "title": "Secure Name/Address Resolution Service (Authoritative Source)",
        "description": "Provide additional data origin authentication and integrity verification artifacts with authoritative name resolution data.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "DNS Security — DNSSEC",
    },
    {
        "id": "SC-21",
        "family": "System and Communications Protection",
        "title": "Secure Name/Address Resolution Service (Recursive or Caching Resolver)",
        "description": "Request and perform data origin authentication and data integrity verification on resolution responses.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "DNS Security — Resolver Validation",
    },
    {
        "id": "SC-22",
        "family": "System and Communications Protection",
        "title": "Architecture and Provisioning for Name/Address Resolution Service",
        "description": "Ensure name/address resolution services are fault-tolerant and implement role separation.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "DNS Architecture — Redundancy",
    },
    {
        "id": "SC-23",
        "family": "System and Communications Protection",
        "title": "Session Authenticity",
        "description": "Protect the authenticity of communications sessions.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Session Management — CSRF/Token Protection",
    },
    {
        "id": "SC-28",
        "family": "System and Communications Protection",
        "title": "Protection of Information at Rest",
        "description": "Protect the confidentiality and integrity of information at rest.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Data Lake — Encryption at Rest (AES-256)",
    },
    {
        "id": "SC-39",
        "family": "System and Communications Protection",
        "title": "Process Isolation",
        "description": "Maintain a separate execution domain for each executing system process.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Container Security — Process Isolation",
    },
    # =========================================================================
    # SI — System and Information Integrity
    # =========================================================================
    {
        "id": "SI-1",
        "family": "System and Information Integrity",
        "title": "Policy and Procedures",
        "description": "Develop, document, and disseminate system and information integrity policy.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Settings > Integrity Policies",
    },
    {
        "id": "SI-2",
        "family": "System and Information Integrity",
        "title": "Flaw Remediation",
        "description": "Identify, report, and correct system flaws within defined time periods.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Vulnerability Management — Patching",
    },
    {
        "id": "SI-3",
        "family": "System and Information Integrity",
        "title": "Malicious Code Protection",
        "description": "Implement malicious code protection mechanisms at system entry and exit points.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Container Security — Malware Scanning",
    },
    {
        "id": "SI-4",
        "family": "System and Information Integrity",
        "title": "System Monitoring",
        "description": "Monitor the system to detect attacks, indicators of compromise, and unauthorized connections.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "SIEM Module / UEBA",
    },
    {
        "id": "SI-5",
        "family": "System and Information Integrity",
        "title": "Security Alerts, Advisories, and Directives",
        "description": "Receive system security alerts and advisories on an ongoing basis.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Threat Intel Module — Advisory Feed",
    },
    {
        "id": "SI-6",
        "family": "System and Information Integrity",
        "title": "Security and Privacy Function Verification",
        "description": "Verify the correct operation of security and privacy functions.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "CI/CD — Security Function Tests",
    },
    {
        "id": "SI-7",
        "family": "System and Information Integrity",
        "title": "Software, Firmware, and Information Integrity",
        "description": "Employ integrity verification tools to detect unauthorized changes.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Supply Chain — Integrity Verification / SBOM",
    },
    {
        "id": "SI-8",
        "family": "System and Information Integrity",
        "title": "Spam Protection",
        "description": "Employ spam protection mechanisms at system entry and exit points.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Email Security — Spam Filtering",
    },
    {
        "id": "SI-10",
        "family": "System and Information Integrity",
        "title": "Information Input Validation",
        "description": "Check the validity of information inputs to the system.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "API Security — Input Validation",
    },
    {
        "id": "SI-11",
        "family": "System and Information Integrity",
        "title": "Error Handling",
        "description": "Generate error messages that provide information necessary for corrective actions without revealing exploitable information.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "API Security — Error Handling",
    },
    {
        "id": "SI-12",
        "family": "System and Information Integrity",
        "title": "Information Management and Retention",
        "description": "Manage and retain information within the system in accordance with applicable laws.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Data Lake — Retention Policies",
    },
    {
        "id": "SI-16",
        "family": "System and Information Integrity",
        "title": "Memory Protection",
        "description": "Implement controls to protect system memory from unauthorized code execution.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Container Security — Memory Protection",
    },
    # =========================================================================
    # PM — Program Management
    # =========================================================================
    {
        "id": "PM-1",
        "family": "Program Management",
        "title": "Information Security Program Plan",
        "description": "Develop and disseminate an organization-wide information security program plan.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — Security Program",
    },
    {
        "id": "PM-2",
        "family": "Program Management",
        "title": "Information Security Program Leadership Role",
        "description": "Appoint a senior agency information security officer.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Organization Settings — CISO Assignment",
    },
    {
        "id": "PM-3",
        "family": "Program Management",
        "title": "Information Security and Privacy Resources",
        "description": "Include security resources in capital planning and investment control.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification — Budget Planning",
    },
    {
        "id": "PM-4",
        "family": "Program Management",
        "title": "Plan of Action and Milestones Process",
        "description": "Implement a process to ensure POA&M items are tracked and resolved.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — POA&M Workflow",
    },
    {
        "id": "PM-5",
        "family": "Program Management",
        "title": "System Inventory",
        "description": "Develop and maintain an inventory of organizational systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Asset Management Module",
    },
    {
        "id": "PM-6",
        "family": "Program Management",
        "title": "Measures of Performance",
        "description": "Develop, monitor, and report on security and privacy performance measures.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Metrics Dashboard",
    },
    {
        "id": "PM-7",
        "family": "Program Management",
        "title": "Enterprise Architecture",
        "description": "Develop and maintain an enterprise architecture with consideration for information security.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Threat Modeling — Architecture Review",
    },
    {
        "id": "PM-8",
        "family": "Program Management",
        "title": "Critical Infrastructure Plan",
        "description": "Address information security issues in the development of a critical infrastructure plan.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "OT Security Module",
    },
    {
        "id": "PM-9",
        "family": "Program Management",
        "title": "Risk Management Strategy",
        "description": "Develop a comprehensive strategy to manage risk to organizational operations.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification — Strategy",
    },
    {
        "id": "PM-10",
        "family": "Program Management",
        "title": "Authorization Process",
        "description": "Manage the security and privacy state of organizational systems through authorization.",
        "priority": "P2",
        "baseline": "moderate",
        "pysoar_mapping": "Compliance Module — ATO Lifecycle",
    },
    {
        "id": "PM-11",
        "family": "Program Management",
        "title": "Mission and Business Process Definition",
        "description": "Define organizational mission and business processes with consideration for information security.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Risk Quantification — Business Impact",
    },
    {
        "id": "PM-12",
        "family": "Program Management",
        "title": "Insider Threat Program",
        "description": "Implement an insider threat program that includes a cross-discipline threat team.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "UEBA / ITDR — Insider Threat Detection",
    },
    {
        "id": "PM-13",
        "family": "Program Management",
        "title": "Security and Privacy Workforce",
        "description": "Establish a security and privacy workforce development and improvement program.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Training Management / Phishing Sim",
    },
    {
        "id": "PM-14",
        "family": "Program Management",
        "title": "Testing, Training, and Monitoring",
        "description": "Implement a testing, training, and monitoring process for organizational systems.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Simulation Module / Continuous Monitoring",
    },
    {
        "id": "PM-15",
        "family": "Program Management",
        "title": "Security and Privacy Groups and Associations",
        "description": "Establish and institutionalize contact with security groups and associations.",
        "priority": "P3",
        "baseline": "moderate",
        "pysoar_mapping": "Threat Intel — ISAC/ISAO Integration",
    },
    {
        "id": "PM-16",
        "family": "Program Management",
        "title": "Threat Awareness Program",
        "description": "Implement a threat awareness program that includes a cross-organization information-sharing capability.",
        "priority": "P1",
        "baseline": "moderate",
        "pysoar_mapping": "Threat Intel Module / Dark Web Monitoring",
    },
]

# Helper: index controls by ID for quick lookup
CONTROLS_BY_ID = {ctrl["id"]: ctrl for ctrl in FEDRAMP_MODERATE_CONTROLS}

# Helper: group controls by family
CONTROLS_BY_FAMILY = {}
for _ctrl in FEDRAMP_MODERATE_CONTROLS:
    CONTROLS_BY_FAMILY.setdefault(_ctrl["family"], []).append(_ctrl)

# Family codes for reference
FAMILY_CODES = {
    "AC": "Access Control",
    "AT": "Awareness and Training",
    "AU": "Audit and Accountability",
    "CA": "Security Assessment and Authorization",
    "CM": "Configuration Management",
    "CP": "Contingency Planning",
    "IA": "Identification and Authentication",
    "IR": "Incident Response",
    "MA": "Maintenance",
    "MP": "Media Protection",
    "PE": "Physical and Environmental Protection",
    "PL": "Planning",
    "PS": "Personnel Security",
    "RA": "Risk Assessment",
    "SA": "System and Services Acquisition",
    "SC": "System and Communications Protection",
    "SI": "System and Information Integrity",
    "PM": "Program Management",
}
