"""Hunting notebook service for investigation document management"""

import json
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional, Any
from pathlib import Path


@dataclass
class NotebookCell:
    """Represents a cell in a hunt notebook"""

    cell_type: str  # markdown, query, result, visualization, code
    content: str
    output: Optional[str] = None
    executed_at: Optional[datetime] = None
    execution_time_ms: Optional[float] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        """Convert cell to dictionary"""
        return {
            "cell_type": self.cell_type,
            "content": self.content,
            "output": self.output,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "execution_time_ms": self.execution_time_ms,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "NotebookCell":
        """Create cell from dictionary"""
        if data.get("executed_at"):
            data["executed_at"] = datetime.fromisoformat(data["executed_at"])
        return cls(**data)


class NotebookService:
    """Service for managing hunt notebooks and investigation documents"""

    # Built-in notebook templates
    INVESTIGATION_REPORT_TEMPLATE = {
        "name": "Investigation Report",
        "description": "Standard investigation report template",
        "cells": [
            NotebookCell(
                cell_type="markdown",
                content="# Investigation Report\n\n*Generated by PySOAR Threat Hunting Module*",
                metadata={"level": 1},
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Executive Summary\n\nProvide a high-level overview of the investigation findings.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Hypothesis\n\nState the hypothesis being investigated.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Methodology\n\nDescribe the investigation approach and data sources used.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Findings\n\nDetail all findings discovered during the investigation.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Recommendations\n\nProvide actionable recommendations based on findings.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Appendix\n\nAdditional supporting evidence and detailed analysis.",
            ),
        ],
    }

    IOC_SWEEP_REPORT_TEMPLATE = {
        "name": "IOC Sweep Report",
        "description": "Template for indicator of compromise hunting",
        "cells": [
            NotebookCell(
                cell_type="markdown",
                content="# IOC Sweep Report\n\n*Indicator of Compromise Search Results*",
                metadata={"level": 1},
            ),
            NotebookCell(
                cell_type="markdown",
                content="## IOCs Searched\n\nList of indicators of compromise included in this sweep.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Results Per IOC\n\nDetailed results for each indicator searched.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Affected Systems\n\nSystems where IOCs were detected.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Timeline\n\nChronological view of IOC detections.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Risk Assessment\n\nOverall risk assessment based on findings.",
            ),
        ],
    }

    BEHAVIORAL_HUNT_REPORT_TEMPLATE = {
        "name": "Behavioral Hunt Report",
        "description": "Template for behavioral anomaly detection",
        "cells": [
            NotebookCell(
                cell_type="markdown",
                content="# Behavioral Hunt Report\n\n*Anomalous Behavior Analysis*",
                metadata={"level": 1},
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Behavior Pattern\n\nDescription of the behavioral pattern being hunted.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Baseline Analysis\n\nNormal baseline behavior for comparison.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Anomalies Detected\n\nBehaviors deviating from baseline.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## False Positives\n\nIdentified false positive detections.",
            ),
            NotebookCell(
                cell_type="markdown",
                content="## True Positives\n\nConfirmed malicious or suspicious behavior.",
            ),
        ],
    }

    def __init__(self, notebook_storage_path: Optional[str] = None):
        """
        Initialize the notebook service

        Args:
            notebook_storage_path: Path to store notebooks. If None, uses in-memory storage.
        """
        self.storage_path = Path(notebook_storage_path) if notebook_storage_path else None
        self.notebooks: dict[str, dict] = {}

    def create_notebook(self, session_id: str, title: str) -> dict:
        """
        Create an empty notebook with default cells

        Args:
            session_id: ID of the hunt session
            title: Title of the notebook

        Returns:
            Created notebook dictionary
        """
        import uuid

        notebook_id = str(uuid.uuid4())

        # Create default cells
        cells = [
            NotebookCell(
                cell_type="markdown",
                content=f"# {title}",
                metadata={"level": 1},
            ),
            NotebookCell(
                cell_type="markdown",
                content="## Investigation Summary\n\n*Hypothesis and scope details will be filled in during investigation*",
            ),
        ]

        notebook = {
            "id": notebook_id,
            "session_id": session_id,
            "title": title,
            "cells": cells,
            "version": 1,
            "is_published": False,
            "published_at": None,
            "created_at": datetime.now(datetime.timezone.utc),
            "updated_at": datetime.now(datetime.timezone.utc),
        }

        self.notebooks[notebook_id] = notebook
        return notebook

    def add_cell(self, notebook_id: str, cell: NotebookCell, position: int = -1) -> dict:
        """
        Add a cell to a notebook

        Args:
            notebook_id: ID of the notebook
            cell: NotebookCell to add
            position: Position to insert (-1 for end)

        Returns:
            Updated notebook dictionary
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        if position == -1:
            notebook["cells"].append(cell)
        else:
            notebook["cells"].insert(position, cell)

        notebook["updated_at"] = datetime.now(datetime.timezone.utc)
        return notebook

    def update_cell(self, notebook_id: str, cell_index: int, content: str) -> dict:
        """
        Update cell content in a notebook

        Args:
            notebook_id: ID of the notebook
            cell_index: Index of the cell to update
            content: New cell content

        Returns:
            Updated notebook dictionary
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        if cell_index < 0 or cell_index >= len(notebook["cells"]):
            raise IndexError(f"Cell index {cell_index} out of range")

        notebook["cells"][cell_index].content = content
        notebook["updated_at"] = datetime.now(datetime.timezone.utc)
        return notebook

    def delete_cell(self, notebook_id: str, cell_index: int) -> dict:
        """
        Remove a cell from a notebook

        Args:
            notebook_id: ID of the notebook
            cell_index: Index of the cell to remove

        Returns:
            Updated notebook dictionary
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        if cell_index < 0 or cell_index >= len(notebook["cells"]):
            raise IndexError(f"Cell index {cell_index} out of range")

        notebook["cells"].pop(cell_index)
        notebook["updated_at"] = datetime.now(datetime.timezone.utc)
        return notebook

    def execute_query_cell(self, notebook_id: str, cell_index: int) -> dict:
        """
        Execute a query cell against the SIEM search service

        Args:
            notebook_id: ID of the notebook
            cell_index: Index of the query cell to execute

        Returns:
            Execution result with output stored in cell
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        if cell_index < 0 or cell_index >= len(notebook["cells"]):
            raise IndexError(f"Cell index {cell_index} out of range")

        cell = notebook["cells"][cell_index]
        if cell.cell_type != "query":
            raise ValueError(f"Cell {cell_index} is not a query cell")

        import asyncio
        import time

        start_time = time.time()

        # Execute query against SIEM search service
        try:
            from src.siem.search import LogSearchService, SearchQuery
            from src.core.database import async_session_factory

            query_text = cell.content.strip()

            async def _run_query():
                async with async_session_factory() as db:
                    search_service = LogSearchService()
                    search_query = SearchQuery(
                        query_text=query_text,
                        size=100,
                        sort_by="timestamp",
                        sort_order="desc",
                    )
                    result = await search_service.search(db, search_query)
                    return result

            search_result = asyncio.run(_run_query())

            # Format results for notebook display
            output_lines = [f"Query: {query_text}", f"Total results: {search_result.total}"]
            for item in search_result.items[:50]:
                ts = item.get("timestamp", "")
                msg = item.get("message", item.get("raw_log", ""))
                output_lines.append(f"  [{ts}] {msg}")

            cell.output = "\n".join(output_lines)

        except Exception as e:
            cell.output = f"Query execution error: {str(e)}"

        cell.executed_at = datetime.now(datetime.timezone.utc)
        cell.execution_time_ms = (time.time() - start_time) * 1000

        notebook["updated_at"] = datetime.now(datetime.timezone.utc)

        return {
            "cell_index": cell_index,
            "execution_time_ms": cell.execution_time_ms,
            "result": cell.output,
        }

    def move_cell(self, notebook_id: str, from_index: int, to_index: int) -> dict:
        """
        Reorder cells in a notebook

        Args:
            notebook_id: ID of the notebook
            from_index: Current position of cell
            to_index: New position for cell

        Returns:
            Updated notebook dictionary
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        if from_index < 0 or from_index >= len(notebook["cells"]):
            raise IndexError(f"Source index {from_index} out of range")
        if to_index < 0 or to_index >= len(notebook["cells"]):
            raise IndexError(f"Target index {to_index} out of range")

        cell = notebook["cells"].pop(from_index)
        notebook["cells"].insert(to_index, cell)
        notebook["updated_at"] = datetime.now(datetime.timezone.utc)

        return notebook

    def get_notebook(self, notebook_id: str) -> dict:
        """
        Get complete notebook with all cells

        Args:
            notebook_id: ID of the notebook

        Returns:
            Complete notebook dictionary
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        return self.notebooks[notebook_id]

    def publish_notebook(self, notebook_id: str) -> dict:
        """
        Mark a notebook as published

        Args:
            notebook_id: ID of the notebook

        Returns:
            Updated notebook dictionary
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        notebook["is_published"] = True
        notebook["published_at"] = datetime.now(datetime.timezone.utc)
        notebook["version"] += 1
        notebook["updated_at"] = datetime.now(datetime.timezone.utc)

        return notebook

    def export_as_json(self, notebook_id: str) -> dict:
        """
        Export notebook as portable JSON format

        Args:
            notebook_id: ID of the notebook

        Returns:
            Notebook in JSON-serializable format
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]

        return {
            "id": notebook["id"],
            "session_id": notebook["session_id"],
            "title": notebook["title"],
            "cells": [cell.to_dict() for cell in notebook["cells"]],
            "version": notebook["version"],
            "is_published": notebook["is_published"],
            "published_at": notebook["published_at"].isoformat()
            if notebook["published_at"]
            else None,
            "created_at": notebook["created_at"].isoformat(),
            "updated_at": notebook["updated_at"].isoformat(),
        }

    def export_as_markdown(self, notebook_id: str) -> str:
        """
        Export notebook as markdown document

        Args:
            notebook_id: ID of the notebook

        Returns:
            Notebook as markdown string
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]
        markdown = []

        for cell in notebook["cells"]:
            if cell.cell_type == "markdown":
                markdown.append(cell.content)
            elif cell.cell_type == "query":
                markdown.append(f"```sql\n{cell.content}\n```")
            elif cell.cell_type == "code":
                markdown.append(f"```python\n{cell.content}\n```")
            elif cell.cell_type == "result":
                markdown.append(f"**Results:**\n\n```\n{cell.output}\n```")
            elif cell.cell_type == "visualization":
                markdown.append(f"*Visualization: {cell.metadata.get('chart_type', 'chart')}*")

            markdown.append("\n")

        return "\n".join(markdown)

    def export_as_html(self, notebook_id: str) -> str:
        """
        Export notebook as standalone HTML report

        Args:
            notebook_id: ID of the notebook

        Returns:
            Notebook as HTML string
        """
        if notebook_id not in self.notebooks:
            raise ValueError(f"Notebook {notebook_id} not found")

        notebook = self.notebooks[notebook_id]

        html = [
            "<!DOCTYPE html>",
            "<html>",
            "<head>",
            '<meta charset="UTF-8">',
            f"<title>{notebook['title']}</title>",
            "<style>",
            "body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 40px; }",
            "h1, h2, h3 { color: #2c3e50; }",
            "code { background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; }",
            "pre { background-color: #f4f4f4; padding: 10px; border-radius: 5px; overflow-x: auto; }",
            "table { border-collapse: collapse; width: 100%; }",
            "th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }",
            "th { background-color: #f0f0f0; }",
            ".metadata { color: #7f8c8d; font-size: 0.9em; }",
            "</style>",
            "</head>",
            "<body>",
            f"<h1>{notebook['title']}</h1>",
            f'<p class="metadata">Generated on {notebook["updated_at"].isoformat()}</p>',
        ]

        for cell in notebook["cells"]:
            if cell.cell_type == "markdown":
                # Simple markdown to HTML conversion
                content = cell.content.replace("\n", "</p><p>")
                html.append(f"<p>{content}</p>")
            elif cell.cell_type == "query":
                html.append("<h4>Query:</h4>")
                html.append(f"<pre><code>{cell.content}</code></pre>")
                if cell.output:
                    html.append("<h4>Results:</h4>")
                    html.append(f"<pre>{cell.output}</pre>")
            elif cell.cell_type == "code":
                html.append("<h4>Code:</h4>")
                html.append(f"<pre><code>{cell.content}</code></pre>")
            elif cell.cell_type == "visualization":
                chart_type = cell.metadata.get("chart_type", "chart")
                html.append(f"<p><em>Visualization: {chart_type}</em></p>")

        html.extend(["</body>", "</html>"])

        return "\n".join(html)

    def create_from_template(
        self, template_name: str, session_id: str, parameters: dict
    ) -> dict:
        """
        Create notebook pre-populated with template queries and markdown

        Args:
            template_name: Name of the template to use
            session_id: ID of the hunt session
            parameters: Parameters to customize the template

        Returns:
            Created notebook from template
        """
        import uuid

        # Select template
        if template_name == "investigation_report":
            template = self.INVESTIGATION_REPORT_TEMPLATE
        elif template_name == "ioc_sweep":
            template = self.IOC_SWEEP_REPORT_TEMPLATE
        elif template_name == "behavioral_hunt":
            template = self.BEHAVIORAL_HUNT_REPORT_TEMPLATE
        else:
            raise ValueError(f"Unknown template: {template_name}")

        notebook_id = str(uuid.uuid4())
        title = parameters.get("title", template["name"])

        # Create notebook with template cells
        notebook = {
            "id": notebook_id,
            "session_id": session_id,
            "title": title,
            "cells": [
                NotebookCell(
                    cell_type=cell.cell_type,
                    content=cell.content,
                    metadata=cell.metadata.copy(),
                )
                for cell in template["cells"]
            ],
            "version": 1,
            "is_published": False,
            "published_at": None,
            "created_at": datetime.now(datetime.timezone.utc),
            "updated_at": datetime.now(datetime.timezone.utc),
        }

        self.notebooks[notebook_id] = notebook
        return notebook
