// Client
export { apiClient, api } from './client';

// Auth
export { authApi } from './auth';
export type { LoginResponse, UserProfile } from './auth';

// Endpoints
export {
  alertsApi,
  incidentsApi,
  siemApi,
  threatIntelApi,
  huntingApi,
  exposureApi,
  aiApi,
  uebaApi,
  simulationApi,
  deceptionApi,
  remediationApi,
  complianceApi,
  zerotrustApi,
  stigApi,
  auditEvidenceApi,
  dfirApi,
  itdrApi,
  vulnmgmtApi,
  supplychainApi,
  darkwebApi,
  integrationsApi,
  agenticApi,
  playbookApi,
  dlpApi,
  riskquantApi,
  otsecurityApi,
  containerApi,
  privacyApi,
  threatmodelApi,
  apisecurityApi,
  datalakeApi,
  collaborationApi,
  phishingApi,
} from './endpoints';

// Types
export type {
  PaginatedResponse,
  User,
  SeverityLevel,
  AlertStatus,
  IncidentStatus,
  IOCType,
  ThreatLevel,
  Alert,
  Incident,
  SIEMEvent,
  SIEMRule,
  SIEMDashboard,
  ThreatIndicator,
  ThreatIntelFeed,
  EnrichmentResult,
  Hunt,
  HuntFinding,
  ExposureAssessment,
  ExposureItem,
  AttackSurface,
  AIPrediction,
  AnalysisResult,
  UserBehavior,
  RiskScore,
  SimulationCampaign,
  SimulationResult,
  Honeypot,
  Honeytoken,
  RemediationPolicy,
  RemediationAction,
  ComplianceFramework,
  ComplianceControl,
  POAM,
  ZeroTrustPolicy,
  DeviceTrust,
  STIGBenchmark,
  STIGFinding,
  AuditEvidence,
  DFIRCase,
  DFIRTimeline,
  IdentityThreat,
  CredentialMonitor,
  Vulnerability,
  PatchOperation,
  SBOM,
  SBOMComponent,
  VendorAssessment,
  DarkWebAlert,
  Connector,
  Agent,
  Investigation,
  Playbook,
  PlaybookNode,
  DLPPolicy,
  DLPRule,
  DLPIncident,
  RiskScenario,
  LossExceedanceAnalysis,
  OTAsset,
  OTZone,
  ContainerImage,
  ContainerScan,
  DataSubjectRequest,
  PrivacyImpactAssessment,
  ThreatModel,
  AttackTree,
  AttackTreeNode,
  APIEndpoint,
  DataSource,
  DataLakePipeline,
  WarRoom,
  WarRoomMessage,
  ActionItem,
  PhishingCampaign,
  PhishingResult,
} from './types';
